server {
    listen       8080;
    listen  [::]:8080;
    server_name  localhost;

    gzip on;
    error_page  404 /usr/share/nginx/html/404.html;
    # /cv (and /cv/) render the cv pdf inline
    location ~ ^/cv/?$ {
        root  /usr/share/nginx/html;
        try_files /cv/max-mitchell-cv.pdf =404;
    }

    location / {
        root   /usr/share/nginx/html;
        index index.htm index.html;
        try_files $uri $uri/ $uri.html =404;
    }
}